import { Eccl, Mask, Mode } from './types.ts';
export declare class QRCodeGenerator {
    readonly text: string;
    mode: Mode;
    eccl: Eccl;
    private _version;
    mask: Mask;
    error: string;
    errorSubcode: string;
    private bitsData;
    private qtyBlocks;
    private bytesCorrectionPerBlock;
    private genpoly;
    private bitsFieldDataQty;
    private positionAlignmentPatterns;
    private data;
    private codewordsData;
    private codewordsQR;
    matrix: (number | null)[][];
    constructor(text: string, mode: Mode, eccl: Eccl, version: number, mask: Mask);
    get version(): number;
    set version(version: number);
    private get needsVerInfo();
    private fixedInfoVersion;
    textToData(): void;
    dataToCodewords(): void;
    makeCodewordsQR(): void;
    private makeCodewordVersion;
    private makeCodewordFormat;
    makeMatrix(): void;
    private maskTest;
}
